# Generated by Django 5.2.5 on 2026-01-25 04:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DWLRStation',
            fields=[
                ('station_code', models.CharField(max_length=30, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(blank=True, max_length=200)),
                ('state', models.CharField(blank=True, max_length=100)),
                ('district', models.CharField(blank=True, max_length=100)),
                ('block', models.CharField(blank=True, max_length=100)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('aquifer_type', models.CharField(blank=True, max_length=50)),
                ('well_depth', models.FloatField(blank=True, null=True)),
                ('elevation', models.FloatField(blank=True, null=True)),
                ('installation_date', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('last_data_update', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['state', 'district', 'name'],
                'indexes': [models.Index(fields=['state', 'district'], name='monitoring__state_22800e_idx'), models.Index(fields=['is_active'], name='monitoring__is_acti_a43e78_idx')],
            },
        ),
        migrations.CreateModel(
            name='GroundwaterResource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calculation_date', models.DateField()),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('estimated_recharge', models.FloatField(blank=True, null=True)),
                ('recharge_rate', models.FloatField(blank=True, null=True)),
                ('current_storage', models.FloatField(blank=True, null=True)),
                ('available_storage', models.FloatField(blank=True, null=True)),
                ('storage_percentage', models.FloatField(blank=True, null=True)),
                ('trend', models.CharField(blank=True, choices=[('rising', 'Rising'), ('falling', 'Falling'), ('stable', 'Stable')], max_length=20)),
                ('trend_magnitude', models.FloatField(blank=True, null=True)),
                ('alert_status', models.CharField(choices=[('critical', 'Critical'), ('warning', 'Warning'), ('normal', 'Normal'), ('good', 'Good')], default='normal', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resources', to='monitoring.dwlrstation')),
            ],
            options={
                'ordering': ['-calculation_date'],
                'indexes': [models.Index(fields=['station', 'calculation_date'], name='monitoring__station_05d992_idx'), models.Index(fields=['alert_status'], name='monitoring__alert_s_a1b95a_idx')],
            },
        ),
        migrations.CreateModel(
            name='WaterLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('depth', models.FloatField()),
                ('water_level_elevation', models.FloatField(blank=True, null=True)),
                ('data_source', models.CharField(default='CGWB_API', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='water_levels', to='monitoring.dwlrstation')),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['station', 'timestamp'], name='monitoring__station_b7b88c_idx'), models.Index(fields=['timestamp'], name='monitoring__timesta_18ba88_idx')],
                'unique_together': {('station', 'timestamp')},
            },
        ),
    ]
